### ISSUE TITLE
Can we cut a version or release?

### ISSUE THREAD

**Issue by herbygillot** [craftvscruft/tfrefactor#6]
I'm interested in adding `tfrefactor` to [MacPorts](https://www.macports.org), but it would be ideal to have a version tag or release to work with.

**Comment by raymyers** [comment]
Thanks for your interest, @herbygillot! I will get a versioning scheme together for you.

**Comment by herbygillot** [comment]
Ok, thanks in advance.

**Comment by raymyers** [comment]
Sorry for the delay.

@herbygillot I've tagged release/v0.0.1, does that work for your needs? In the future I'd like to have the patch version increment on every PR merge but it's manual for now.

**Comment by herbygillot** [comment]
Thank you @raymyers, this works perfectly.

`tfrefactor` can now be installed on macOS via Macports.

Here's its port page: 
https://ports.macports.org/port/tfrefactor/

Manual vs automatic version increments is entirely up to you, so no worries there.

**Comment by herbygillot** [comment]
We could probably add this to the documentation - but I'll close this issue for now.  Thank you.
